/**
 * lib/api/insightApi.ts
 * ─────────────────────────────────────────────────────────────────────
 * All client-side API functions for the /api/insights endpoints.
 *
 * Functions:
 *   getInsights(opts?)          → GET   /api/insights
 *   getInsightsEngine(opts?)    → GET   /api/insights/engine
 *   markInsightsRead()          → PATCH /api/insights
 *   generateInsights()          → POST  /api/insights/generate
 *
 * Example:
 *   import { getInsights, markInsightsRead } from '@/lib/api/insightApi';
 *
 *   const { insights, unreadCount } = await getInsights();
 *   await markInsightsRead();
 */

import { get, post, patch, buildQuery } from './apiClient';
import type { InsightsSummaryDTO } from '@/types/api';
import type { InsightsEngineOutput } from '@/types/engine';

// ─── Response shapes ──────────────────────────────────────────────────────────

export interface MarkReadResponse {
  markedRead: number;
}

export interface GenerateInsightsResponse {
  message: string;
  created: number;
  month:   number;
  year:    number;
}

// ─── Input shapes ─────────────────────────────────────────────────────────────

export interface GetInsightsOptions {
  unreadOnly?: boolean;
}

export interface GetEngineOptions {
  month?: number;
  year?:  number;
}

// ─── API functions ────────────────────────────────────────────────────────────

/**
 * getInsights
 * Fetch stored insight cards (notification-style) from the database.
 * These are pre-generated by the rules engine (via generateInsights).
 *
 * @example
 * const { insights, unreadCount } = await getInsights();
 * console.log(`${unreadCount} unread insights`);
 *
 * // Fetch only unread
 * const { insights: unread } = await getInsights({ unreadOnly: true });
 */
export async function getInsights(
  opts: GetInsightsOptions = {},
): Promise<InsightsSummaryDTO> {
  const qs = buildQuery({
    unreadOnly: opts.unreadOnly ?? false,
  });
  return get<InsightsSummaryDTO>(`/api/insights${qs}`);
}

/**
 * getInsightsEngine
 * Run the full real-time Insights Engine for the current user.
 * Returns rich computed output: WoW/MoM trends, goal probabilities,
 * text advice cards, spending patterns, and a financial health score.
 *
 * This is more expensive than getInsights() — call once on page load,
 * not on every render.
 *
 * @example
 * const engine = await getInsightsEngine();
 * console.log('Health score:', engine.score.overall);
 * engine.advice.forEach(a => console.log(a.headline));
 * engine.goalProbabilities.forEach(g => console.log(g.title, g.probability));
 */
export async function getInsightsEngine(
  opts: GetEngineOptions = {},
): Promise<InsightsEngineOutput> {
  const now = new Date();
  const qs  = buildQuery({
    month:  opts.month ?? now.getMonth() + 1,
    year:   opts.year  ?? now.getFullYear(),
  });
  return get<InsightsEngineOutput>(`/api/insights/engine${qs}`);
}

/**
 * markInsightsRead
 * Mark all insight cards as read for the current user.
 * Returns the count of rows updated.
 *
 * @example
 * const { markedRead } = await markInsightsRead();
 * console.log(`Marked ${markedRead} insights as read`);
 */
export async function markInsightsRead(): Promise<MarkReadResponse> {
  return patch<MarkReadResponse>('/api/insights', {});
}

/**
 * generateInsights
 * Trigger the rules engine to (re)generate insight cards for the current month.
 * Idempotent — safe to call multiple times or from a cron job.
 *
 * @example
 * const { created } = await generateInsights();
 * console.log(`${created} new insight(s) generated`);
 */
export async function generateInsights(): Promise<GenerateInsightsResponse> {
  return post<GenerateInsightsResponse>('/api/insights/generate', {});
}
